name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write  # wymagane dla Trusted Publishers
  contents: read

jobs:
  publish:
    environment: release
    name: Publish if tag is GPG signed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags --force

      - name: Import public GPG key
        run: echo "$GPG_PUBLIC_KEY" | gpg --import
        env:
          GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}

      - name: Verify GPG tag signature
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          echo "Verifying tag: $TAG"
          git verify-tag "$TAG"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install build tools
        run: pip install build

      - name: Build package
        run: python -m build

      - name: Publish to PyPI (Trusted Publishers)
        uses: pypa/gh-action-pypi-publish@v1.8.10
        with:
          packages-dir: dist
          verify-metadata: true
